# Generated by Django 5.0.4 on 2024-05-07 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('batch', models.IntegerField()),
                ('major', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Absent', 'Absent'), ('Present', 'Present'), ('Sick', 'Sick'), ('Permit', 'Permit')], default='Absent', max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Absent', 'Absent'), ('Present', 'Present'), ('Sick', 'Sick'), ('Permit', 'Permit')], max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FacultyView.student')),
            ],
            options={
                'unique_together': {('student', 'date')},
            },
        ),
    ]
